name: CI

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: php-actions/composer@v1 # or alternative dependency management
      with:
        command: composer require --dev phpunit/phpunit
    
    - name: PHPUnit (php-actions)
      uses: php-actions/phpunit@v1
      with:
        config: vendor/phpunit/phpunit/phpunit.xml
      
    # - name: PHPUnit run
    #   run: |
    #     sudo chmod 0775 vendor/phpunit/phpunit/phpunit
    #     ./vendor/bin/phpunit tests

    # - name: PHPUnit (php-actions)
    #   uses: php-actions/phpunit@v1
    #   with:
    #     config: vendor/phpunit/phpunit/phpunit.xml
