name: CI

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Composer (php-actions)
      uses: php-actions/composer@v1
    
    - name: PHPUnit
      uses: chindit/actions-phpunit-symfony@master

    # - name: PHPUnit (php-actions)
    #   uses: php-actions/phpunit@v1
    #   with:
    #     config: vendor/phpunit/phpunit/phpunit.xml
      
    # - name: PHPUnit run
    #   run: |
    #     sudo chmod 0775 vendor/phpunit/phpunit/phpunit
    #     ./vendor/bin/phpunit tests

    # - name: PHPUnit (php-actions)
    #   uses: php-actions/phpunit@v1
    #   with:
    #     config: vendor/phpunit/phpunit/phpunit.xml
